name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🌟 Welcome! Thank you for opening this issue. We're here to assist you. Feel free to share your thoughts and ideas! ✨"
        pr-message: "🌟 Welcome! Thank you for your pull request. We appreciate your contribution. Let's collaborate to make it even better! ✨"
